// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/guilleamutio/go4money/ent/account"
	"github.com/guilleamutio/go4money/ent/schema"
	"github.com/guilleamutio/go4money/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescOwner is the schema descriptor for owner field.
	accountDescOwner := accountFields[0].Descriptor()
	// account.OwnerValidator is a validator for the "owner" field. It is called by the builders before save.
	account.OwnerValidator = accountDescOwner.Validators[0].(func(string) error)
	// accountDescBalance is the schema descriptor for balance field.
	accountDescBalance := accountFields[1].Descriptor()
	// account.DefaultBalance holds the default value on creation for the balance field.
	account.DefaultBalance = accountDescBalance.Default.(int64)
	// accountDescCurrency is the schema descriptor for currency field.
	accountDescCurrency := accountFields[2].Descriptor()
	// account.DefaultCurrency holds the default value on creation for the currency field.
	account.DefaultCurrency = accountDescCurrency.Default.(string)
	// account.CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	account.CurrencyValidator = accountDescCurrency.Validators[0].(func(string) error)
	// accountDescCreatedAt is the schema descriptor for created_at field.
	accountDescCreatedAt := accountFields[3].Descriptor()
	// account.DefaultCreatedAt holds the default value on creation for the created_at field.
	account.DefaultCreatedAt = accountDescCreatedAt.Default.(time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[1].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescPasswordChangedAt is the schema descriptor for password_changed_at field.
	userDescPasswordChangedAt := userFields[2].Descriptor()
	// user.DefaultPasswordChangedAt holds the default value on creation for the password_changed_at field.
	user.DefaultPasswordChangedAt = userDescPasswordChangedAt.Default.(time.Time)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(time.Time)
}
