host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a UI for go4money API.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger go4money API
  version: "1.0"
paths:
  /api/v1/users/createUser:
    get:
      consumes:
      - application/json
      description: create user in database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: createUser
      tags:
      - user
swagger: "2.0"
